## LOAD AND ANALYZE A BATCH OF SIMULATIONS 
<li> Counterfactual inference is performed separately on 4 different groups of subjects: females < 65 years, males <65 years, females > 65 years and males > 65 years </li>
<li> The code reads the simulations  of a specific subgroup (e.g., subgroup 1 (women below 65 years)) and analyses them to find stably T2D, stably non-T2D, improved and worsened patients </li>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
simulation_group_filepath=r".\simulations\...csv"
group_unique_comb_filepath=r'.\combinations\...csv'
stableNOT2D_filepath=r'stableNOT2D\df_stableNOT2D_g1.csv'
stableT2D_filepath=r'stableT2D\df_stableT2D_g1.csv'
improved_filepath=r'improved\df_improved_g1.csv'
worsened_filepath=r'worsened\df_worsened_g1.csv'
T2Dfactual_filepath=r'T2Dfactual\df_T2Dfactual_g1.csv'
T2Dcounterfactual_filepath=r'T2Dcounterfactual\df_T2Dcounterfactual_g1.csv'
overlapped_filepath=r'overlapped\df_overlapped_g1.csv'
overlapped2_filepath=r'overlapped\df_overlappedT2D_g1.csv'

thr=0.07 #set discrimination threshold for risk of T2D onset definition based on test prevalence of T2D

In [2]:
#read a batch of simulations (e.g., femals <65 years)
sim_g1=pd.read_csv(simulation_group_filepath,delimiter=',')
sim_g1

,LDL,BMI,Pressure,Diabetes,TG,HDL,FBS,BMI_final,FBS_final,Pdiabetes_min,Pdiabetes_max,Pdiabetes_star_min,Pdiabetes_star_max,Pdelta_min,Pdelta_max
0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,0,0,0,0,0,0,1,0,1,0.000000e+00,4.545001e-11,0.000000e+00,2.102331e-16,-4.544980e-11,0.000000e+00
2,0,0,0,0,0,1,0,0,0,0.000000e+00,5.792397e-63,0.000000e+00,1.031914e-75,-5.792397e-63,0.000000e+00
3,0,0,0,0,0,1,1,0,0,0.000000e+00,2.348474e-10,0.000000e+00,2.155342e-73,-2.348474e-10,1.730616e-73
4,0,0,0,0,0,1,1,0,1,0.000000e+00,2.348474e-10,0.000000e+00,4.076468e-15,-2.348434e-10,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,1,4,1,0,0,1,1,4,1,8.752260e-51,8.690565e-11,1.570202e-75,2.043804e-15,-8.690361e-11,-8.361537e-51
405,1,4,1,0,1,0,0,3,0,1.498934e-132,1.743676e-12,4.684471e-297,4.611728e-15,-1.743676e-12,4.611728e-15
406,1,4,1,0,1,0,0,4,0,1.498934e-132,1.743676e-12,1.093747e-187,7.884567e-19,-1.743676e-12,-1.498934e-132
407,1,4,1,0,1,0,1,4,0,2.534834e-100,7.365188e-12,2.599433e-186,2.098386e-18,-7.365188e-12,-2.534834e-100
408,1,4,1,0,1,0,1,4,1,2.534834e-100,7.365188e-12,2.010271e-132,3.217073e-16,-7.365188e-12,-2.534834e-100

In [3]:
sim_g1.describe()

,LDL,BMI,Pressure,Diabetes,TG,HDL,FBS,BMI_final,FBS_final,Pdiabetes_min,Pdiabetes_max,Pdiabetes_star_min,Pdiabetes_star_max,Pdelta_min,Pdelta_max
count,409.000000,409.000000,409.000000,409.000000,409.000000,409.000000,409.000000,409.000000,409.000000,4.090000e+02,4.090000e+02,4.080000e+02,4.080000e+02,4.080000e+02,4.080000e+02
mean,0.349633,2.151589,0.572127,0.229829,0.371638,0.476773,0.643032,1.735941,0.420538,9.509924e-02,9.509946e-02,2.742103e-02,2.378779e-01,-6.546046e-02,1.449965e-01
std,0.477438,1.235307,0.495376,0.421238,0.483834,0.500072,0.479692,1.284792,0.494250,1.253453e-01,1.253456e-01,9.794917e-02,3.091666e-01,9.706776e-02,2.694328e-01
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-5.000002e-01,-4.999987e-01
25%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,6.768499e-51,1.005839e-08,8.003470e-247,8.853856e-14,-1.030417e-01,-6.238211e-51
50%,0.000000,2.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,6.249974e-02,6.250001e-02,5.363492e-07,5.142000e-02,-4.609876e-02,3.559331e-07
75%,1.000000,3.000000,1.000000,0.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.538461e-01,1.538463e-01,1.492889e-02,4.532208e-01,-3.138034e-09,3.139698e-01
max,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.999953e-01,1.000000e+00

In [5]:
#read the dataset that stores all the subgroup unique patient combinations (as created after running CountDiscreteCombinations.ipynb)
#each row describes a unique combination of input features
#the 'count' column stores the number of patients described by that combination
unique_comb=pd.read_csv(group_unique_comb_filepath,delimiter=',')
unique_comb=unique_comb.drop(['Unnamed: 0'], axis=1)
unique_comb

,age,sex,Pressure,BMI,BMI_final,LDL,HDL,TG,FBS,FBS_final,Diabetes,count
0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,64
1,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,62
2,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,61
3,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,52
4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,52
...,...,...,...,...,...,...,...,...,...,...,...,...
404,0.0,0.0,1.0,3.0,2.0,1.0,1.0,1.0,0.0,0.0,0.0,1
405,0.0,0.0,0.0,2.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1
406,0.0,0.0,0.0,4.0,3.0,1.0,1.0,0.0,1.0,1.0,0.0,1
407,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1
408,0.0,0.0,1.0,3.0,3.0,0.0,1.0,0.0,0.0,0.0,1.0,1

In [6]:
# Merge simulations dataframe and the dataframes that count the number of unique rows based on common columns
df = pd.merge(sim_g1, unique_comb, on=['BMI','Pressure','FBS','LDL','HDL','TG','Diabetes','FBS_final','BMI_final'], how='inner')  
print(df)

     LDL  BMI  Pressure  Diabetes  TG  HDL  FBS  BMI_final  FBS_final  \
0      0    0         0         0   0    0    0          0          0
1      0    0         0         0   0    0    1          0          1
2      0    0         0         0   0    1    0          0          0
3      0    0         0         0   0    1    1          0          0
4      0    0         0         0   0    1    1          0          1
..   ...  ...       ...       ...  ..  ...  ...        ...        ...
404    1    4         1         0   0    1    1          4          1
405    1    4         1         0   1    0    0          3          0
406    1    4         1         0   1    0    0          4          0
407    1    4         1         0   1    0    1          4          0
408    1    4         1         0   1    0    1          4          1

     Pdiabetes_min  Pdiabetes_max  Pdiabetes_star_min  Pdiabetes_star_max  \
0     0.000000e+00   0.000000e+00        0.000000e+00        0.000000e+00
1     0.000000e+00   4.545001e-11        0.000000e+00        2.102331e-16
2     0.000000e+00   5.792397e-63        0.000000e+00        1.031914e-75
3     0.000000e+00   2.348474e-10        0.000000e+00        2.155342e-73
4     0.000000e+00   2.348474e-10        0.000000e+00        4.076468e-15
..             ...            ...                 ...                 ...
404   8.752260e-51   8.690565e-11        1.570202e-75        2.043804e-15
405  1.498934e-132   1.743676e-12       4.684471e-297        4.611728e-15
406  1.498934e-132   1.743676e-12       1.093747e-187        7.884567e-19
407  2.534834e-100   7.365188e-12       2.599433e-186        2.098386e-18
408  2.534834e-100   7.365188e-12       2.010271e-132        3.217073e-16

       Pdelta_min     Pdelta_max  age  sex  count
0    0.000000e+00   0.000000e+00  0.0  0.0      6
1   -4.544980e-11   0.000000e+00  0.0  0.0      4
2   -5.792397e-63   0.000000e+00  0.0  0.0     30
3   -2.348474e-10   1.730616e-73  0.0  0.0      4
4   -2.348434e-10   0.000000e+00  0.0  0.0     14
..            ...            ...  ...  ...    ...
404 -8.690361e-11  -8.361537e-51  0.0  0.0      1
405 -1.743676e-12   4.611728e-15  0.0  0.0      1
406 -1.743676e-12 -1.498934e-132  0.0  0.0      1
407 -7.365188e-12 -2.534834e-100  0.0  0.0      2
408 -7.365188e-12 -2.534834e-100  0.0  0.0      2

[409 rows x 18 columns]

## Intervention efficacy

Analisy of the efficacy of intervention. First, pb in the factual and counterfactual worlds are compared wrt to a discrimination threshold (0.07). Then, the intervention is deemed effective for all patients whose pb of T2D onset is above threshold in the factual world and below threshold in the counterfactual world.

<b> Factual world </b>

In [12]:
#set a flag equal to 1 if the pb is above threshold, equal to 0 if the pb is below thr and equal to 2 in any other case.
df['out_R']=2;#default n.a.
df.loc[df["Pdiabetes_min"]>=thr, 'out_R']=1 # above thr
df.loc[df["Pdiabetes_max"]<thr, 'out_R']=0 #below thr
print('- #patients unique combinations with \033[1mpb_factual below thr\033[0m:', df.loc[df['out_R']==0].shape[0])
print('Count on the basis of actual absence/presence of T2D:\n',df.loc[df['out_R']==0]['Diabetes'].value_counts())
print('Related #subjects:',df.loc[df['out_R']==0]['count'].sum())

print('\n- #patients unique combinations with \033[1mpb_factual above thr\033[0m:', df.loc[df['out_R']==1].shape[0])
print('Count on the basis of actual absence/presence of T2D:\n',df.loc[df['out_R']==1]['Diabetes'].value_counts())
print('Related #subjects:',df.loc[df['out_R']==1]['count'].sum())

print('\n- #patients unique combinations with \033[1mpb_factual equal to the thr\033[0m:', df.loc[df['out_R']==2].shape[0])
print('Count on the basis of actual absence/presence of T2D:\n',df.loc[df['out_R']==2]['Diabetes'].value_counts())
print('Related #subjects:',df.loc[df['out_R']==2]['count'].sum())

- #patients unique combinations with pb_factual below thr: 207
Count on the basis of actual absence/presence of T2D:
 0    186
1     21
Name: Diabetes, dtype: int64
Related #subjects: 1349

- #patients unique combinations with pb_factual above thr: 202
Count on the basis of actual absence/presence of T2D:
 0    129
1     73
Name: Diabetes, dtype: int64
Related #subjects: 1106

- #patients unique combinations with pb_factual equal to the thr: 0
Count on the basis of actual absence/presence of T2D:
 Series([], Name: Diabetes, dtype: int64)
Related #subjects: 0

<b> Counterfactual world </b>

In [13]:
#set a flag equal to 1 if the pb interval is completely above threshold, equal to 0 if the pb interval is completely below thr
#and equal to 2 if the probability interval overlaps with the threshold.
df['out_C']=2;#default n.a.
df.loc[df["Pdiabetes_star_min"]>=thr, 'out_C']=1 # above thr
df.loc[df["Pdiabetes_star_max"]<thr, 'out_C']=0 #below thr
print('- #patients unique combinations with \033[1mpb interval counterfactual completely below thr\033[0m:', df.loc[df['out_C']==0].shape[0])
print('Count on the basis of actual absence/presence of T2D:\n',df.loc[df['out_C']==0]['Diabetes'].value_counts())
print('Related #subjects:',df.loc[df['out_C']==0]['count'].sum())

print('\n- #patients unique combinations with \033[1mpb interval counterfactual completely above thr\033[0m:', df.loc[df['out_C']==1].shape[0])
print('Count on the basis of actual absence/presence of T2D:\n',df.loc[df['out_C']==1]['Diabetes'].value_counts())
print('Related #subjects:',df.loc[df['out_C']==1]['count'].sum())

print('\n- #patients unique combinations with \033[1mpb interval counterfactual that overlaps with the thr\033[0m:', df.loc[df['out_C']==2].shape[0])
print('Count on the basis of actual absence/presence of T2D:\n',df.loc[df['out_C']==2]['Diabetes'].value_counts())
print('Related #subjects:',df.loc[df['out_C']==2]['count'].sum())

- #patients unique combinations with pb interval counterfactual completely below thr: 215
Count on the basis of actual absence/presence of T2D:
 0    192
1     23
Name: Diabetes, dtype: int64
Related #subjects: 1131

- #patients unique combinations with pb interval counterfactual completely above thr: 39
Count on the basis of actual absence/presence of T2D:
 0    20
1    19
Name: Diabetes, dtype: int64
Related #subjects: 274

- #patients unique combinations with pb interval counterfactual that overlaps with the thr: 155
Count on the basis of actual absence/presence of T2D:
 0    103
1     52
Name: Diabetes, dtype: int64
Related #subjects: 1050

In [21]:
 #patients above thr in the factual world
T2Dfact=df.loc[df['out_R']==1,:]
T2Dfact.to_csv(T2Dfactual_filepath)
#patients above thr in the counterfactual world
T2Dcounterfact=df.loc[df['out_C']==1,:] 
T2Dcounterfact.to_csv(T2Dcounterfactual_filepath)

In [22]:
#patients to which we cannot assign a label of risk as their output probability interval in the counterfactual world overlaps with the threshold
overlapped=df.loc[df['out_C']==2,:] 
overlapped.to_csv(overlapped_filepath)

In [23]:
#subset of patients whose output probability in the factual world is above the threshold (high risk) 
#but whose output probability interval that overlaps with the threshold in the counterfactual world 
overlapped2=df.loc[((df['out_C']==2)&(df['out_R']==1)),:]
overlapped2.to_csv(overlapped2_filepath)

<b> Patients that remain stably below thr in both worlds </b>

In [14]:
#select patients whose pb of T2D onset is below thr in both factual and counterfactual world
stableNOT2D=df.loc[(df['out_R']==0)&(df['out_C']==0),:]
print('\033[1mStable no T2D\033[0m')
print('#unique combinations: ',stableNOT2D.shape[0])
print('Count on the basis of actual absence/presence of T2D:\n', stableNOT2D['Diabetes'].value_counts())
print('\nRelated #subjects: ',stableNOT2D['count'].sum())
print('Count on the basis of actual absence/presence of T2D:')
print('0: ',stableNOT2D.loc[stableNOT2D['Diabetes']==0,:]['count'].sum())
print('1: ',stableNOT2D.loc[stableNOT2D['Diabetes']==1,:]['count'].sum())
stableNOT2D.to_csv(stableNOT2D_filepath)

Stable no T2D
#unique combinations:  169
Count on the basis of actual absence/presence of T2D:
 0    155
1     14
Name: Diabetes, dtype: int64

Related #subjects:  1012
Count on the basis of actual absence/presence of T2D:
0:  996
1:  16

<b> Patients that remain stably above thr in both worlds </b>

In [15]:
#select patients whose pb of T2D onset is above thr in both factual and counterfactual world
stableT2D=df.loc[(df['out_R']==1)&(df['out_C']==1),:]
print('\033[1mStable T2D\033[0m')
print('#unique combinations: ',stableT2D.shape[0])
print('Count on the basis of actual absence/presence of T2D:\n', stableT2D['Diabetes'].value_counts())
print('\nRelated #subjects: ',stableT2D['count'].sum())
print('Count on the basis of actual absence/presence of T2D:')
print('0: ',stableT2D.loc[stableT2D['Diabetes']==0,:]['count'].sum())
print('1: ',stableT2D.loc[stableT2D['Diabetes']==1,:]['count'].sum())
stableT2D.to_csv(stableT2D_filepath)

Stable T2D
#unique combinations:  38
Count on the basis of actual absence/presence of T2D:
 0    19
1    19
Name: Diabetes, dtype: int64

Related #subjects:  271
Count on the basis of actual absence/presence of T2D:
0:  213
1:  58

<b> Patients that are above thr in the factual world and completely below thr in the counterfactual world </b>

In [16]:
#select patients whose pb of T2D onset is above thr in factual world and completely below thr in the counterfactual world
#for these patients the intervention is deemed effective
improved=df.loc[(df['out_R']==1)&(df['out_C']==0),:]
print('\033[1mImproved patients\033[0m')
print('#unique combinations: ',improved.shape[0])
print('Count on the basis of actual absence/presence of T2D:\n', improved['Diabetes'].value_counts())
print('\nRelated #subjects: ',improved['count'].sum())
print('Count on the basis of actual absence/presence of T2D:')
print('0: ',improved.loc[improved['Diabetes']==0,:]['count'].sum())
print('1: ',improved.loc[improved['Diabetes']==1,:]['count'].sum())
#save corresponding dataframe
improved.to_csv(improved_filepath)

Improved patients
#unique combinations:  46
Count on the basis of actual absence/presence of T2D:
 0    37
1     9
Name: Diabetes, dtype: int64

Related #subjects:  119
Count on the basis of actual absence/presence of T2D:
0:  108
1:  11

<b> Patients that are below thr in the factual world and completely above thr in the counterfactual world </b>

In [19]:
#select patients whose pb of T2D onset is below thr in factual world and completely above thr in the counterfactual world
#for these patients the intervention went wrong
worsened=df.loc[(df['out_R']==0)&(df['out_C']==1),:]
print('\033[1mWorsened patients\033[0m')
print('#unique combinations: ',worsened.shape[0])
print('Count on the basis of actual absence/presence of T2D:\n', worsened['Diabetes'].value_counts())
print('\nRelated #subjects: ',worsened['count'].sum())
print('Count on the basis of actual absence/presence of T2D:')
print('0: ',worsened.loc[worsened['Diabetes']==0,:]['count'].sum())
print('1: ',worsened.loc[worsened['Diabetes']==1,:]['count'].sum())
#save corresponding dataframe
worsened.to_csv(worsened_filepath)

Worsened patients
#unique combinations:  1
Count on the basis of actual absence/presence of T2D:
 0    1
Name: Diabetes, dtype: int64

Related #subjects:  3
Count on the basis of actual absence/presence of T2D:
0:  3
1:  0